{"name": "Запрос без номера заказа возвращает ошибку", "status": "passed", "description": "Запрос получения заказа без трэк номера возвращает код ответа 400 Bad Request и \"message\": {OrderMessages.NOT_ENOUGH_DATA_GET_ORDER}", "steps": [{"name": "Отправляем запрос без трэк номера заказа", "status": "passed", "start": 1758134177252, "stop": 1758134177587}], "start": 1758134177252, "stop": 1758134177590, "uuid": "a8736fc1-0a82-495b-9c68-b2d61076bded", "historyId": "3a32b9b2ee65db092cdf2bb06b559a78", "testCaseId": "3a32b9b2ee65db092cdf2bb06b559a78", "fullName": "tests.test_get_orders.TestGetOrderByNumber#test_error_get_order_without_track_number", "labels": [{"name": "subSuite", "value": "class TestGetOrderByNumber: Получить заказ по его трек номеру"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_get_orders"}, {"name": "host", "value": "MacBook-Pro-Ivan.local"}, {"name": "thread", "value": "7206-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_get_orders"}], "titlePath": ["tests", "test_get_orders.py", "TestGetOrderByNumber"]}